[package]
name = "evw-swc-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_core = { workspace = true }
sha2 = "0.10"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = "symbols"
